version: "3.8"

volumes:
  mysql_data:
  build_folder:


services:
  mysqldb:
    build: ./backend/db
    env_file:
      - "./backend/db/db.env"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend/backend
    command: >
      bash -c "python wait_mysql.py &&
               python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8080" &&
               
    ports:
      - "8080:8080"
    volumes:
      - ./backend/backend:/app
    depends_on:
      - mysqldb
    links:
      - mysqldb


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: [ "yarn", "start" ]
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/frontend
    tty: true

  nginx:
    build: ./nginx
    ports:
      - 80:8080
    # volumes:
    #   - static_volume:/backend/staticfiles
    #   - media_volume:/backend/mediafiles
    #   - build_folder:/var/www/frontend
    depends_on:
      - backend
      - frontend